# 策略组相关
pr: &pr {type: select, proxies: [🚀 节点选择, 🇭🇰 香港, 🇼🇸 台湾, 🇯🇵 日本, 🇸🇬 新加坡, 🇺🇸 美国, DIRECT]}
# 这里是订阅更新和延迟测试相关的
p: &p {type: http, interval: 86400, health-check: {enable: true, url: "http://cp.cloudflare.com", interval: 600}, override: {smux: {enabled: true, protocol: h2mux, max-connections: 16, min-streams: 4, padding: true, brutal-opts: {enabled: true, up: 500, down: 1000, statistic: true}}}}

# https://hub.docker.com/r/xream/sub-store
proxy-providers:
  provider1:
    <<: *p
    url: "http://172.16.1.50:3001/D2UhuYViWtqwddacM4ss/download/collection/AIO"

ipv6: false
log-level: info
allow-lan: true
mixed-port: 7890
unified-delay: true
tcp-concurrent: true
find-process-mode: strict
keep-alive-interval: 600
external-controller: 0.0.0.0:9090

geodata-mode: true
geox-url:
  geoip: "https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/release/geoip-lite.dat"
  geosite: "https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/release/geosite.dat"
  mmdb: "https://raw.gitmirror.com/NobyDa/geoip/release/Private-GeoIP.mmdb"

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      override-destination: true
      ports:
        - 80
        - 8080-8880
    TLS:
      override-destination: true
      ports:
        - 443
        - 8443
    QUIC:
      override-destination: true
      ports:
        - 443
        - 8443

dns:
  enable: true
  prefer-h3: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:53
  ipv6: false
  nameserver:
    - system
    - dhcp://system
  nameserver-policy:
    "geosite:geolocation-!cn":
      - https://doh.apad.pro/dns-query
      - https://dns.cooluc.com/dns-query

proxy-groups:
  - {name: 🚀 节点选择, type: select, proxies: [自动选择, 🇭🇰 香港, 🇼🇸 台湾, 🇯🇵 日本, 🇸🇬 新加坡, 🇺🇸 美国, DIRECT]}
  - {name: 自动选择, type: fallback, include-all-providers: true, interval: 300}
  - {name: Emby, type: select, proxies: [低倍率, 🚀 节点选择, DIRECT]}
  - {name: AI, <<: *pr}
  - {name: Github, <<: *pr}
  - {name: Telegram, <<: *pr}
  - {name: Google, <<: *pr}
  - {name: YouTube, <<: *pr}
  - {name: Tracker, type: select, proxies: [DIRECT, 🇭🇰 香港, 🇼🇸 台湾, 🇯🇵 日本, 🇸🇬 新加坡, 🇺🇸 美国]}
  - {name: 流媒体, <<: *pr}
  - {name: Porns, <<: *pr}
  - {name: Bilibili, type: select, proxies: [DIRECT, 🇭🇰 香港, 🇼🇸 台湾]}
  - {name: 巴哈姆特, type: select, proxies: [🇼🇸 台湾, DIRECT]}
  - {name: Microsoft, <<: *pr}
  - {name: MATCH, <<: *pr}

# 分隔,下面是地区分组
  - {name: 🇭🇰 香港, type: fallback , include-all-providers: true, filter: "(?i)港|hk|hongkong|hong kong"}
  - {name: 🇼🇸 台湾, type: fallback , include-all-providers: true, filter: "(?i)台|tw|taiwan"}
  - {name: 🇯🇵 日本, type: fallback , include-all-providers: true, filter: "(?i)日|jp|japan"}
  - {name: 🇸🇬 新加坡, type: fallback , include-all-providers: true, filter: "(?i)(新|sg|singapore)"}
  - {name: 🇺🇸 美国, type: fallback , include-all-providers: true, filter: "(?i)美|us|unitedstates|united states"}
  - {name: 低倍率, type: fallback , include-all-providers: true, filter: "(?i)0.0"}

rules:
  - RULE-SET,custom_direct,DIRECT
  - GEOSITE,tracker,Tracker
  - RULE-SET,custom_proxy,🚀 节点选择
  - GEOSITE,biliintl,🚀 节点选择
  - RULE-SET,custom_reject,REJECT
  - RULE-SET,adrules,REJECT
  - RULE-SET,ai,AI
  - GEOSITE,youtube,YouTube
  - GEOIP,google,Google
  - GEOSITE,google,Google
  - GEOIP,netflix,流媒体
  - GEOSITE,netflix,流媒体
  - GEOSITE,primevideo,流媒体
  - GEOSITE,disney,流媒体
  - GEOSITE,category-porn,Porns
  - GEOSITE,bilibili,Bilibili
  - GEOIP,telegram,Telegram
  - GEOSITE,telegram,Telegram
  - GEOSITE,github,Github
  - GEOSITE,microsoft,Microsoft
  - GEOSITE,bahamut,巴哈姆特
  - RULE-SET,emby,Emby
  - GEOIP,CN,DIRECT
  - MATCH,MATCH

rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: yaml}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: yaml}
  domaintxt: &domaintxt {type: http, interval: 86400, behavior: domain, format: text}
  classical: &classical {type: http, interval: 86400, behavior: classical, format: text}

# https://wiki.metacubex.one/config/syntax/?h=%E9%80%9A%E9%85%8D%E7%AC%A6#_6
# https://wiki.metacubex.one/config/rule-providers/content/#__tabbed_2_1
rule-providers:
  custom_direct:
    <<: *domain
    url: "https://raw.gitmirror.com/JohnsonRan/CRules/master/lists/custom.yaml"
  custom_proxy:
    <<: *domain
    url: "https://raw.gitmirror.com/JohnsonRan/CRules/master/lists/customProxy.yaml"
  custom_reject:
    <<: *domain
    url: "https://raw.gitmirror.com/JohnsonRan/CRules/master/lists/reject.yaml"
  emby:
    <<: *classical
    url: "https://raw.gitmirror.com/Repcz/Tool/X/Surge/Rules/Emby.list"
  ai:
    <<: *classical
    url: "https://raw.gitmirror.com/EAlyce/conf/main/Rule/OpenAI.list"
  adrules:
    <<: *domaintxt
    url: "https://adrules.top/adrules_domainset.txt"
