mixed-port: 7890
geodata-mode: true
geodata-loader: standard
tcp-concurrent: true
allow-lan: true
bind-address: "*"
ipv6: false
mode: rule
geox-url:
  geoip: "https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/release/geoip.dat"
  geosite: "https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/release/geosite.dat"
  mmdb: "https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/release/country.mmdb"
log-level: info
external-controller: 0.0.0.0:9090
global-client-fingerprint: chrome
profile:
  store-selected: true
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  force-domain:
  - "+.netflix.com"
  - "+.nflxvideo.net"
  - "+.amazonaws.com"
  - "+.media.dssott.com"
  skip-domain:
  - "+.apple.com"
  - Mijia Cloud
  - dlg.io.mi.com
  sniff:
    TLS:
    HTTP:
      ports:
      - 80
      - 8080-8880
      override-destination: true
dns:
  enable: true
  prefer-h3: true
  ipv6: false
  enhanced-mode: redir-host
  nameserver:
    - https://doh.apad.pro/dns-query
    - https://dns.cooluc.com/dns-query
  proxy-server-nameserver:
    - 223.5.5.5
experimental:
  ignore-resolve-fail: true
unified-delay: true