mixed-port: 7890
geodata-mode: true
tcp-concurrent: true
allow-lan: true
bind-address: "*"
ipv6: false
mode: rule
log-level: warning
external-controller: 0.0.0.0:9090
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  sniffing:
    - tls
    - http
  skip-domain:
    - '+.apple.com'
    - 'Mijia Cloud'
    - '+.jd.com'
  force-domain:
    - '+.netflix.com'
    - '+.nflxvideo.net'
    - '+.amazonaws.com'
    - '+.media.dssott.com'
  port-whitelist:
    - 443
    - 80
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - '!CN'
  nameserver:
    - https://223.5.5.5/dns-query
    - https://120.53.53.53/dns-query
  fallback:
    - 'https://8.8.4.4/dns-query#自动选择'
    - 'https://1.0.0.1/dns-query#自动选择'
  proxy-server-nameserver:
    - 223.5.5.5
experimental:
  ignore-resolve-fail: true
