name: Merge Rules

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  merge-and-clean:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install mihomo
      run: |
        version=$(curl -skL https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/version.txt)
        curl -skLo mihomo.deb https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-$version.deb
        sudo dpkg -i mihomo.deb

    - name: Convert AD Rules into mrs
      run: |
        bash scripts/convert.sh ads

    - name: Convert AI Rules into mrs
      run: |
        bash scripts/convert.sh ais

    - name: more mrs
      run: |
        wget https://ruleset.skk.moe/Clash/domainset/speedtest.txt
        mihomo convert-ruleset domain text speedtest.txt speedtest.mrs

    - name: Commit and push changes
      run: |
        mv {*.mrs,ADs_merged.txt,AIs_merged.txt} rules/
        CURRENT_TIME=$(date +"%Y-%m-%d %H:%M")
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git checkout --orphan mihomo
        git rm -rf .
        git add rules/*
        git commit -m "Auto Update $CURRENT_TIME"
        git push -f origin mihomo

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 2