name: Merge Rules

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  merge-and-clean:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install mihomo
      run: |
        version=$(curl -skL https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/version.txt)
        curl -skLo mihomo.deb https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-$version.deb
        sudo dpkg -i mihomo.deb

    - name: Convert AdRules and oisd
      run: |
        curl -skL https://adrules.top/adrules_domainset.txt >> rules.txt
        curl -skL https://big.oisd.nl/domainswild2 >> rules.txt
        curl -skL https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/reject-list.txt >> rules.txt
        cat rules.txt | sed '/^#/d' > combined_raw.txt
        sed -E 's/^[\+\*\.]+//g' combined_raw.txt | grep -v '^$' > normalized.txt
        sort normalized.txt | uniq > unique_domains.txt
        awk '{print "+." $0}' unique_domains.txt > ADs_merged.txt
        mihomo convert-ruleset domain text ADs_merged.txt ADs_merged.mrs

    - name: Convert AWAvenue rules
      run: |
        wget https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.yaml
        mihomo convert-ruleset domain yaml AWAvenue-Ads-Rule-Clash.yaml ADs_AWAvenue.mrs

    - name: more mrs
      run: |
        wget https://ruleset.skk.moe/Clash/domainset/speedtest.txt
        mihomo convert-ruleset domain text speedtest.txt speedtest.mrs

    - name: Commit and push changes
      run: |
        mv {*.mrs,ADs_merged.txt} rules/
        CURRENT_TIME=$(date +"%Y-%m-%d %H:%M")
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git checkout --orphan mihomo
        git rm -rf .
        git add rules/*
        git commit -m "Auto Update $CURRENT_TIME"
        git push -f origin mihomo

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 2